### ISSUE TITLE
Add comparison to UCL - universal configuration language as well

### ISSUE THREAD

**Issue by igor84** [Carpetsmoker/arp242.net#5]
I would really like to hear your comparison between YAML, TOML and UCL.

Link: https://github.com/vstakhov/libucl

**Comment by earonesty** [comment]
- The "automatic array creation" of UCL/nginx sounds like a recipe for an unexpected attack vector at worst... and an unexpected crash at best.
  - The benchmarking is a bit disengenous... since JSON is a subset of UCL, it's simply *not possible* for it to be faster in a fair test.   "nearly the same", i'll buy.  It makes me trust the rest of the site less.
  - Macros can result in the billion-lol attack, and includes, also are unsafe, so it's important to note that UCL is for "trusted sources only"

**Comment by Carpetsmoker** [comment]
Thanks for the suggestion  @igor84, as well as @earonesty for your thoughts.

I removed the entire Alternatives section for now, as I don't have the time or interest to do a comprehensive and fair review. See https://github.com/Carpetsmoker/arp242.net/issues/8#issuecomment-403527157 for a more detailed rationale.
