### ISSUE TITLE
Some help needed porting stdout.write from python2 to python3

### ISSUE THREAD

**Issue by dragoshenron** [Carpetsmoker/arp242.net#9]
Hello,

would be so kind to help me [here](https://github.com/jbuehl/solaredge/issues/101#issuecomment-403392670)?

Thanks a lot in advance!
Alex

**Comment by Carpetsmoker** [comment]
I'm sorry, but I have no idea what that project is, or even what the issue is. I'm not going to spend my spare time reading up on the (fairly long) issue to fix a bug in a project I don't maintain or even care about.

I have plenty of bugs to fix in projects I care about, as well as other things to do in my life ;-)

**Comment by dragoshenron** [comment]
Well,
there is only [one single line of code](https://github.com/jbuehl/solaredge/blob/master/utilities/unhexlify.py) which is causing an issue related to string encoding in python3 and which is perfectly working in python2. The link was provided to give context around that line of code.

As you seems to understand the subject and have time to write an extensive response on stackoverflow and re-publish it on your website, I thought you can have some advice. I was wrong.

You should indeed continue to take care about projects you are interested into.
I will continue to take care about the people behind a community.

Have fun.
